name: Create Toolkit

on:
  workflow_dispatch:

jobs:
  compile_toolkit:
    runs-on: windows-latest
    steps:
      -
        name: Download Inceptor
        uses: actions/checkout@v3
        with:
          repository: 'klezVirus/inceptor'
          submodules: 'recursive'
          path: './inceptor'
          # ref: 'dev' #! Needs to be tested!
      -
        name: Setup Inceptor
        run: |
          cd .\inceptor
          pip install virtualenv wheel
          virtualenv venv
          .\venv\Scripts\activate.bat
          pip install -r requirements.txt
          cd .\inceptor
      -
        uses: mxschmitt/action-tmate@v3

