name: Create Toolkit

on:
  workflow_dispatch:

jobs:
  compile_toolkit:
    runs-on: windows-latest
    steps:
      -
        name: Download Inceptor
        uses: actions/checkout@v3
        with:
          repository: 'klezVirus/inceptor'
          submodules: 'recursive'
          path: './inceptor'
          # ref: 'dev' #! Needs to be tested!
      -
        name: Run Inceptor update-config.py
        run: dir ./inceptor
